# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fewshot/configs/c4_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fewshot/configs/c4_config.proto',
  package='fewshot.configs',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1f\x66\x65wshot/configs/c4_config.proto\x12\x0f\x66\x65wshot.configs\"\xe2\x02\n\x08\x43\x34\x43onfig\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x14\n\x0cnum_channels\x18\x03 \x01(\x05\x12\x13\n\x0bnum_filters\x18\x04 \x03(\x05\x12\x14\n\x0cweight_decay\x18\x05 \x01(\x02\x12\x19\n\x0b\x64\x61ta_format\x18\x06 \x01(\t:\x04NCHW\x12!\n\rnormalization\x18\x07 \x01(\t:\nbatch_norm\x12\x12\n\nnum_groups\x18\x08 \x03(\x05\x12\x0c\n\x04pool\x18\t \x03(\x05\x12\x1b\n\radd_last_relu\x18\n \x01(\x08:\x04true\x12\x1a\n\x0cpool_padding\x18\x0b \x01(\t:\x04SAME\x12\x1e\n\x12\x61\x63tivation_scaling\x18\x0c \x01(\x02:\x02-1\x12\x13\n\x0b\x61\x64\x64_dropout\x18\r \x01(\x08\x12\x14\n\x0c\x64ropout_rate\x18\x0e \x01(\x02\x12\x12\n\nnum_fc_dim\x18\x0f \x03(\x05')
)




_C4CONFIG = _descriptor.Descriptor(
  name='C4Config',
  full_name='fewshot.configs.C4Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='fewshot.configs.C4Config.height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='fewshot.configs.C4Config.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_channels', full_name='fewshot.configs.C4Config.num_channels', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_filters', full_name='fewshot.configs.C4Config.num_filters', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight_decay', full_name='fewshot.configs.C4Config.weight_decay', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_format', full_name='fewshot.configs.C4Config.data_format', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("NCHW").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalization', full_name='fewshot.configs.C4Config.normalization', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("batch_norm").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_groups', full_name='fewshot.configs.C4Config.num_groups', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pool', full_name='fewshot.configs.C4Config.pool', index=8,
      number=9, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add_last_relu', full_name='fewshot.configs.C4Config.add_last_relu', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pool_padding', full_name='fewshot.configs.C4Config.pool_padding', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("SAME").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation_scaling', full_name='fewshot.configs.C4Config.activation_scaling', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add_dropout', full_name='fewshot.configs.C4Config.add_dropout', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dropout_rate', full_name='fewshot.configs.C4Config.dropout_rate', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_fc_dim', full_name='fewshot.configs.C4Config.num_fc_dim', index=14,
      number=15, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=407,
)

DESCRIPTOR.message_types_by_name['C4Config'] = _C4CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C4Config = _reflection.GeneratedProtocolMessageType('C4Config', (_message.Message,), dict(
  DESCRIPTOR = _C4CONFIG,
  __module__ = 'fewshot.configs.c4_config_pb2'
  # @@protoc_insertion_point(class_scope:fewshot.configs.C4Config)
  ))
_sym_db.RegisterMessage(C4Config)


# @@protoc_insertion_point(module_scope)
