# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fewshot/configs/environment_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fewshot/configs/environment_config.proto',
  package='fewshot.configs',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n(fewshot/configs/environment_config.proto\x12\x0f\x66\x65wshot.configs\"\x88\x03\n\x11\x45nvironmentConfig\x12\x13\n\x0b\x64\x61ta_folder\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x0f\n\x07results\x18\x03 \x01(\t\x12\x12\n\ncheckpoint\x18\x04 \x01(\t\x12\x13\n\x0btrain_split\x18\x64 \x01(\t\x12\x11\n\tval_split\x18\x65 \x01(\t\x12\x12\n\ntest_split\x18\x66 \x01(\t\x12\x16\n\x0etrain_fs_split\x18g \x01(\t\x12\x14\n\x0cval_fs_split\x18h \x01(\t\x12\x15\n\rtest_fs_split\x18i \x01(\t\x12\x13\n\nimage_size\x18\xc8\x01 \x01(\x05\x12\x12\n\tcrop_size\x18\xc9\x01 \x01(\x05\x12\x14\n\x0brandom_crop\x18\xca\x01 \x01(\x08\x12\x14\n\x0brandom_flip\x18\xcb\x01 \x01(\x08\x12\x15\n\x0crandom_color\x18\xcc\x01 \x01(\x08\x12\x16\n\rrandom_rotate\x18\xcd\x01 \x01(\x08\x12\x11\n\x08mean_pix\x18\xac\x02 \x03(\x02\x12\x10\n\x07std_pix\x18\xad\x02 \x03(\x02')
)




_ENVIRONMENTCONFIG = _descriptor.Descriptor(
  name='EnvironmentConfig',
  full_name='fewshot.configs.EnvironmentConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_folder', full_name='fewshot.configs.EnvironmentConfig.data_folder', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='fewshot.configs.EnvironmentConfig.dataset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='fewshot.configs.EnvironmentConfig.results', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkpoint', full_name='fewshot.configs.EnvironmentConfig.checkpoint', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_split', full_name='fewshot.configs.EnvironmentConfig.train_split', index=4,
      number=100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_split', full_name='fewshot.configs.EnvironmentConfig.val_split', index=5,
      number=101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_split', full_name='fewshot.configs.EnvironmentConfig.test_split', index=6,
      number=102, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_fs_split', full_name='fewshot.configs.EnvironmentConfig.train_fs_split', index=7,
      number=103, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_fs_split', full_name='fewshot.configs.EnvironmentConfig.val_fs_split', index=8,
      number=104, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_fs_split', full_name='fewshot.configs.EnvironmentConfig.test_fs_split', index=9,
      number=105, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_size', full_name='fewshot.configs.EnvironmentConfig.image_size', index=10,
      number=200, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crop_size', full_name='fewshot.configs.EnvironmentConfig.crop_size', index=11,
      number=201, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_crop', full_name='fewshot.configs.EnvironmentConfig.random_crop', index=12,
      number=202, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_flip', full_name='fewshot.configs.EnvironmentConfig.random_flip', index=13,
      number=203, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_color', full_name='fewshot.configs.EnvironmentConfig.random_color', index=14,
      number=204, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_rotate', full_name='fewshot.configs.EnvironmentConfig.random_rotate', index=15,
      number=205, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_pix', full_name='fewshot.configs.EnvironmentConfig.mean_pix', index=16,
      number=300, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='std_pix', full_name='fewshot.configs.EnvironmentConfig.std_pix', index=17,
      number=301, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=454,
)

DESCRIPTOR.message_types_by_name['EnvironmentConfig'] = _ENVIRONMENTCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnvironmentConfig = _reflection.GeneratedProtocolMessageType('EnvironmentConfig', (_message.Message,), dict(
  DESCRIPTOR = _ENVIRONMENTCONFIG,
  __module__ = 'fewshot.configs.environment_config_pb2'
  # @@protoc_insertion_point(class_scope:fewshot.configs.EnvironmentConfig)
  ))
_sym_db.RegisterMessage(EnvironmentConfig)


# @@protoc_insertion_point(module_scope)
