# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fewshot/configs/episode_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fewshot/configs/episode_config.proto',
  package='fewshot.configs',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n$fewshot/configs/episode_config.proto\x12\x0f\x66\x65wshot.configs\"\xca\x07\n\rEpisodeConfig\x12\x1d\n\x0c\x62\x61se_sampler\x18\x01 \x01(\t:\x07\x66\x65wshot\x12\x0f\n\x04nway\x18\x02 \x01(\x05:\x01\x35\x12\x11\n\x06nquery\x18\x03 \x01(\x05:\x01\x35\x12\x14\n\tnshot_max\x18\x04 \x01(\x05:\x01\x35\x12\x1b\n\x0fmax_num_per_cls\x18\x05 \x01(\x05:\x02\x32\x30\x12\x16\n\x0esemisupervised\x18\x06 \x01(\x08\x12\x18\n\x0blabel_ratio\x18\x07 \x01(\x02:\x03\x30.1\x12\x12\n\x06maxlen\x18\x08 \x01(\x05:\x02\x34\x30\x12\x14\n\x0c\x61llow_repeat\x18\t \x01(\x08\x12\x11\n\tuse_query\x18\n \x01(\x08\x12\x19\n\x0b\x66ix_unknown\x18\x0b \x01(\x08:\x04true\x12\x14\n\x0chierarchical\x18\x64 \x01(\x08\x12\x1b\n\x13use_class_hierarchy\x18\x65 \x01(\x08\x12\x11\n\x06nstage\x18\x66 \x01(\x05:\x01\x31\x12\x15\n\x07\x62lender\x18g \x01(\t:\x04hard\x12\x1c\n\x10\x62lur_window_size\x18h \x01(\x05:\x02\x31\x30\x12\x16\n\x0b\x62lur_stride\x18i \x01(\x05:\x01\x33\x12\x14\n\tblur_nrun\x18j \x01(\x05:\x01\x32\x12\x1f\n\x12markov_switch_prob\x18k \x01(\x02:\x03\x30.5\x12\x1b\n\x13mix_class_hierarchy\x18l \x01(\x08\x12\x17\n\x0fuse_same_family\x18m \x01(\x08\x12\x14\n\x0cshuffle_time\x18n \x01(\x08\x12\x1f\n\x17use_new_class_hierarchy\x18o \x01(\x08\x12\x16\n\x08prob_new\x18\xc8\x01 \x01(\x02:\x03\x30.4\x12\x17\n\tcrp_alpha\x18\xc9\x01 \x01(\x02:\x03\x30.5\x12\x15\n\tcrp_theta\x18\xca\x01 \x01(\x02:\x01\x31\x12\x1d\n\x11\x64istractor_nquery\x18\xac\x02 \x01(\x05:\x01\x32\x12\x1c\n\x10\x64istractor_nshot\x18\xad\x02 \x01(\x05:\x01\x32\x12\x1b\n\x0f\x64istractor_nway\x18\xae\x02 \x01(\x05:\x01\x35\x12\x13\n\nrandom_box\x18\x90\x03 \x01(\x08\x12 \n\x11random_background\x18\x91\x03 \x01(\t:\x04none\x12\'\n\x1erandom_background_random_apply\x18\x92\x03 \x01(\x08\x12(\n\x1crandom_background_apply_prob\x18\x93\x03 \x01(\x02:\x01\x31\x12)\n random_background_random_context\x18\x94\x03 \x01(\x08\x12+\n\x1erandom_background_gaussian_std\x18\x95\x03 \x01(\x02:\x02-1')
)




_EPISODECONFIG = _descriptor.Descriptor(
  name='EpisodeConfig',
  full_name='fewshot.configs.EpisodeConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_sampler', full_name='fewshot.configs.EpisodeConfig.base_sampler', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("fewshot").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nway', full_name='fewshot.configs.EpisodeConfig.nway', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nquery', full_name='fewshot.configs.EpisodeConfig.nquery', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nshot_max', full_name='fewshot.configs.EpisodeConfig.nshot_max', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_num_per_cls', full_name='fewshot.configs.EpisodeConfig.max_num_per_cls', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=20,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='semisupervised', full_name='fewshot.configs.EpisodeConfig.semisupervised', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_ratio', full_name='fewshot.configs.EpisodeConfig.label_ratio', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxlen', full_name='fewshot.configs.EpisodeConfig.maxlen', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=40,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allow_repeat', full_name='fewshot.configs.EpisodeConfig.allow_repeat', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_query', full_name='fewshot.configs.EpisodeConfig.use_query', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fix_unknown', full_name='fewshot.configs.EpisodeConfig.fix_unknown', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hierarchical', full_name='fewshot.configs.EpisodeConfig.hierarchical', index=11,
      number=100, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_class_hierarchy', full_name='fewshot.configs.EpisodeConfig.use_class_hierarchy', index=12,
      number=101, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nstage', full_name='fewshot.configs.EpisodeConfig.nstage', index=13,
      number=102, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blender', full_name='fewshot.configs.EpisodeConfig.blender', index=14,
      number=103, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("hard").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blur_window_size', full_name='fewshot.configs.EpisodeConfig.blur_window_size', index=15,
      number=104, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blur_stride', full_name='fewshot.configs.EpisodeConfig.blur_stride', index=16,
      number=105, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blur_nrun', full_name='fewshot.configs.EpisodeConfig.blur_nrun', index=17,
      number=106, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='markov_switch_prob', full_name='fewshot.configs.EpisodeConfig.markov_switch_prob', index=18,
      number=107, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mix_class_hierarchy', full_name='fewshot.configs.EpisodeConfig.mix_class_hierarchy', index=19,
      number=108, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_same_family', full_name='fewshot.configs.EpisodeConfig.use_same_family', index=20,
      number=109, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shuffle_time', full_name='fewshot.configs.EpisodeConfig.shuffle_time', index=21,
      number=110, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_new_class_hierarchy', full_name='fewshot.configs.EpisodeConfig.use_new_class_hierarchy', index=22,
      number=111, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prob_new', full_name='fewshot.configs.EpisodeConfig.prob_new', index=23,
      number=200, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.4),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crp_alpha', full_name='fewshot.configs.EpisodeConfig.crp_alpha', index=24,
      number=201, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crp_theta', full_name='fewshot.configs.EpisodeConfig.crp_theta', index=25,
      number=202, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distractor_nquery', full_name='fewshot.configs.EpisodeConfig.distractor_nquery', index=26,
      number=300, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distractor_nshot', full_name='fewshot.configs.EpisodeConfig.distractor_nshot', index=27,
      number=301, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distractor_nway', full_name='fewshot.configs.EpisodeConfig.distractor_nway', index=28,
      number=302, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_box', full_name='fewshot.configs.EpisodeConfig.random_box', index=29,
      number=400, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_background', full_name='fewshot.configs.EpisodeConfig.random_background', index=30,
      number=401, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("none").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_background_random_apply', full_name='fewshot.configs.EpisodeConfig.random_background_random_apply', index=31,
      number=402, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_background_apply_prob', full_name='fewshot.configs.EpisodeConfig.random_background_apply_prob', index=32,
      number=403, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_background_random_context', full_name='fewshot.configs.EpisodeConfig.random_background_random_context', index=33,
      number=404, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_background_gaussian_std', full_name='fewshot.configs.EpisodeConfig.random_background_gaussian_std', index=34,
      number=405, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=1028,
)

DESCRIPTOR.message_types_by_name['EpisodeConfig'] = _EPISODECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EpisodeConfig = _reflection.GeneratedProtocolMessageType('EpisodeConfig', (_message.Message,), dict(
  DESCRIPTOR = _EPISODECONFIG,
  __module__ = 'fewshot.configs.episode_config_pb2'
  # @@protoc_insertion_point(class_scope:fewshot.configs.EpisodeConfig)
  ))
_sym_db.RegisterMessage(EpisodeConfig)


# @@protoc_insertion_point(module_scope)
