# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fewshot/configs/hybrid_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fewshot/configs/hybrid_config.proto',
  package='fewshot.configs',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n#fewshot/configs/hybrid_config.proto\x12\x0f\x66\x65wshot.configs\"\x87\x03\n\x0cHybridConfig\x12!\n\x13use_pred_beta_gamma\x18\x01 \x01(\x08:\x04true\x12\x1e\n\x10use_feature_fuse\x18\x02 \x01(\x08:\x04true\x12#\n\x15use_feature_fuse_gate\x18\x03 \x01(\x08:\x04true\x12!\n\x13use_feature_scaling\x18\x04 \x01(\x08:\x04true\x12&\n\x17use_feature_memory_only\x18\x05 \x01(\x08:\x05\x66\x61lse\x12$\n\x15use_element_fuse_gate\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\x1c\n\x0creadout_type\x18\x07 \x01(\t:\x06linear\x12%\n\x16skip_unk_memory_update\x18\x64 \x01(\x08:\x05\x66\x61lse\x12\x15\n\x07use_ssl\x18\x65 \x01(\x08:\x04true\x12&\n\x18use_ssl_beta_gamma_write\x18\x66 \x01(\x08:\x04true\x12\x1a\n\x0cuse_ssl_temp\x18g \x01(\x08:\x04true')
)




_HYBRIDCONFIG = _descriptor.Descriptor(
  name='HybridConfig',
  full_name='fewshot.configs.HybridConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_pred_beta_gamma', full_name='fewshot.configs.HybridConfig.use_pred_beta_gamma', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_feature_fuse', full_name='fewshot.configs.HybridConfig.use_feature_fuse', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_feature_fuse_gate', full_name='fewshot.configs.HybridConfig.use_feature_fuse_gate', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_feature_scaling', full_name='fewshot.configs.HybridConfig.use_feature_scaling', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_feature_memory_only', full_name='fewshot.configs.HybridConfig.use_feature_memory_only', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_element_fuse_gate', full_name='fewshot.configs.HybridConfig.use_element_fuse_gate', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readout_type', full_name='fewshot.configs.HybridConfig.readout_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("linear").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skip_unk_memory_update', full_name='fewshot.configs.HybridConfig.skip_unk_memory_update', index=7,
      number=100, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_ssl', full_name='fewshot.configs.HybridConfig.use_ssl', index=8,
      number=101, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_ssl_beta_gamma_write', full_name='fewshot.configs.HybridConfig.use_ssl_beta_gamma_write', index=9,
      number=102, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_ssl_temp', full_name='fewshot.configs.HybridConfig.use_ssl_temp', index=10,
      number=103, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=448,
)

DESCRIPTOR.message_types_by_name['HybridConfig'] = _HYBRIDCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HybridConfig = _reflection.GeneratedProtocolMessageType('HybridConfig', (_message.Message,), dict(
  DESCRIPTOR = _HYBRIDCONFIG,
  __module__ = 'fewshot.configs.hybrid_config_pb2'
  # @@protoc_insertion_point(class_scope:fewshot.configs.HybridConfig)
  ))
_sym_db.RegisterMessage(HybridConfig)


# @@protoc_insertion_point(module_scope)
