# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fewshot/configs/lstm_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fewshot/configs/lstm_config.proto',
  package='fewshot.configs',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n!fewshot/configs/lstm_config.proto\x12\x0f\x66\x65wshot.configs\"F\n\nLSTMConfig\x12\x12\n\nhidden_dim\x18\x01 \x01(\x05\x12\x11\n\x06nstack\x18\x02 \x01(\x05:\x01\x31\x12\x11\n\tlayernorm\x18\x03 \x01(\x08')
)




_LSTMCONFIG = _descriptor.Descriptor(
  name='LSTMConfig',
  full_name='fewshot.configs.LSTMConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hidden_dim', full_name='fewshot.configs.LSTMConfig.hidden_dim', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nstack', full_name='fewshot.configs.LSTMConfig.nstack', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layernorm', full_name='fewshot.configs.LSTMConfig.layernorm', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['LSTMConfig'] = _LSTMCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LSTMConfig = _reflection.GeneratedProtocolMessageType('LSTMConfig', (_message.Message,), dict(
  DESCRIPTOR = _LSTMCONFIG,
  __module__ = 'fewshot.configs.lstm_config_pb2'
  # @@protoc_insertion_point(class_scope:fewshot.configs.LSTMConfig)
  ))
_sym_db.RegisterMessage(LSTMConfig)


# @@protoc_insertion_point(module_scope)
