# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fewshot/configs/mann_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fewshot/configs/mann_config.proto',
  package='fewshot.configs',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n!fewshot/configs/mann_config.proto\x12\x0f\x66\x65wshot.configs\"\x88\x05\n\nMANNConfig\x12\x12\n\nmemory_dim\x18\x01 \x01(\x05\x12\x16\n\x0e\x63ontroller_dim\x18\x02 \x01(\x05\x12\x11\n\tnum_slots\x18\x03 \x01(\x05\x12\x11\n\tnum_reads\x18\x04 \x01(\x05\x12\x12\n\nnum_writes\x18\x05 \x01(\x05\x12\x14\n\x0cmemory_decay\x18\x06 \x01(\x02\x12\x1d\n\x0f\x63ontroller_type\x18\x07 \x01(\t:\x04lstm\x12\x1e\n\x16memory_attention_steps\x18\x08 \x01(\x05\x12\x17\n\x0fnum_write_steps\x18\t \x01(\x05\x12\x17\n\x0fnum_delay_steps\x18\n \x01(\x05\x12(\n\x15memory_attention_type\x18\x0b \x01(\t:\tsymmetric\x12\x1e\n\x13\x61\x66\x66inity_prop_steps\x18\x0c \x01(\x05:\x01\x35\x12(\n\x18\x61\x66\x66inity_prop_similarity\x18\r \x01(\t:\x06\x63osine\x12\"\n\x15\x61\x66\x66inity_prop_damping\x18\x0e \x01(\x02:\x03\x30.5\x12\x1f\n\x10memory_layernorm\x18\x0f \x01(\x08:\x05\x66\x61lse\x12#\n\x14\x63ontroller_layernorm\x18\x10 \x01(\x08:\x05\x66\x61lse\x12\x1c\n\x11\x63ontroller_nstack\x18\x11 \x01(\x05:\x01\x32\x12\x1f\n\x0fsimilarity_type\x18\x12 \x01(\t:\x06\x63osine\x12\x19\n\rquery_key_dim\x18\x13 \x01(\x05:\x02-1\x12\x1c\n\x0creadout_type\x18\x14 \x01(\t:\x06linear\x12\x1a\n\x0cuse_unk_gate\x18\x15 \x01(\x08:\x04true\x12\x1b\n\ruse_feat_gate\x18\x16 \x01(\x08:\x04true')
)




_MANNCONFIG = _descriptor.Descriptor(
  name='MANNConfig',
  full_name='fewshot.configs.MANNConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='memory_dim', full_name='fewshot.configs.MANNConfig.memory_dim', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controller_dim', full_name='fewshot.configs.MANNConfig.controller_dim', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_slots', full_name='fewshot.configs.MANNConfig.num_slots', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_reads', full_name='fewshot.configs.MANNConfig.num_reads', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_writes', full_name='fewshot.configs.MANNConfig.num_writes', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory_decay', full_name='fewshot.configs.MANNConfig.memory_decay', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controller_type', full_name='fewshot.configs.MANNConfig.controller_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("lstm").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory_attention_steps', full_name='fewshot.configs.MANNConfig.memory_attention_steps', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_write_steps', full_name='fewshot.configs.MANNConfig.num_write_steps', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_delay_steps', full_name='fewshot.configs.MANNConfig.num_delay_steps', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory_attention_type', full_name='fewshot.configs.MANNConfig.memory_attention_type', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("symmetric").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='affinity_prop_steps', full_name='fewshot.configs.MANNConfig.affinity_prop_steps', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='affinity_prop_similarity', full_name='fewshot.configs.MANNConfig.affinity_prop_similarity', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("cosine").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='affinity_prop_damping', full_name='fewshot.configs.MANNConfig.affinity_prop_damping', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory_layernorm', full_name='fewshot.configs.MANNConfig.memory_layernorm', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controller_layernorm', full_name='fewshot.configs.MANNConfig.controller_layernorm', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controller_nstack', full_name='fewshot.configs.MANNConfig.controller_nstack', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='similarity_type', full_name='fewshot.configs.MANNConfig.similarity_type', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("cosine").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query_key_dim', full_name='fewshot.configs.MANNConfig.query_key_dim', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readout_type', full_name='fewshot.configs.MANNConfig.readout_type', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("linear").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_unk_gate', full_name='fewshot.configs.MANNConfig.use_unk_gate', index=20,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_feat_gate', full_name='fewshot.configs.MANNConfig.use_feat_gate', index=21,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=703,
)

DESCRIPTOR.message_types_by_name['MANNConfig'] = _MANNCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MANNConfig = _reflection.GeneratedProtocolMessageType('MANNConfig', (_message.Message,), dict(
  DESCRIPTOR = _MANNCONFIG,
  __module__ = 'fewshot.configs.mann_config_pb2'
  # @@protoc_insertion_point(class_scope:fewshot.configs.MANNConfig)
  ))
_sym_db.RegisterMessage(MANNConfig)


# @@protoc_insertion_point(module_scope)
