# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fewshot/configs/memory_net_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fewshot/configs/memory_net_config.proto',
  package='fewshot.configs',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\'fewshot/configs/memory_net_config.proto\x12\x0f\x66\x65wshot.configs\"\xf3\x03\n\x0fMemoryNetConfig\x12\x13\n\x0bmax_classes\x18\x01 \x01(\x05\x12\x13\n\x0bradius_init\x18\x02 \x01(\x02\x12\r\n\x05\x61lpha\x18\x03 \x01(\x02\x12\x11\n\tmax_items\x18\x04 \x01(\x05\x12\x16\n\x0elog_sigma_init\x18\x05 \x01(\x02\x12\x17\n\x0flog_lambda_init\x18\x06 \x01(\x02\x12\x12\n\nmax_stages\x18\x07 \x01(\x05\x12\x13\n\x0b\x62uffer_size\x18\x08 \x01(\x05\x12\x16\n\x0e\x62uffer_dropout\x18\t \x01(\x08\x12\x1d\n\nsimilarity\x18\n \x01(\t:\teuclidean\x12\x19\n\x11radius_init_write\x18\x0b \x01(\x02\x12\x1d\n\x0eunknown_logits\x18\x0c \x01(\t:\x05radii\x12\x15\n\ttemp_init\x18\r \x01(\x02:\x02\x31\x30\x12\x1a\n\x0c\x64\x65nse_update\x18\x0e \x01(\x08:\x04true\x12\x19\n\rgru_bias_init\x18\x0f \x01(\x02:\x02-2\x12 \n\x11normalize_feature\x18\x10 \x01(\x08:\x05\x66\x61lse\x12&\n\x18use_ssl_beta_gamma_write\x18\x11 \x01(\x08:\x04true\x12\x19\n\x0b\x66ix_unknown\x18\x12 \x01(\x08:\x04true\x12\x16\n\nunknown_id\x18\x13 \x01(\x05:\x02\x34\x30')
)




_MEMORYNETCONFIG = _descriptor.Descriptor(
  name='MemoryNetConfig',
  full_name='fewshot.configs.MemoryNetConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_classes', full_name='fewshot.configs.MemoryNetConfig.max_classes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius_init', full_name='fewshot.configs.MemoryNetConfig.radius_init', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='fewshot.configs.MemoryNetConfig.alpha', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_items', full_name='fewshot.configs.MemoryNetConfig.max_items', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_sigma_init', full_name='fewshot.configs.MemoryNetConfig.log_sigma_init', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_lambda_init', full_name='fewshot.configs.MemoryNetConfig.log_lambda_init', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_stages', full_name='fewshot.configs.MemoryNetConfig.max_stages', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buffer_size', full_name='fewshot.configs.MemoryNetConfig.buffer_size', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buffer_dropout', full_name='fewshot.configs.MemoryNetConfig.buffer_dropout', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='similarity', full_name='fewshot.configs.MemoryNetConfig.similarity', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("euclidean").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius_init_write', full_name='fewshot.configs.MemoryNetConfig.radius_init_write', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown_logits', full_name='fewshot.configs.MemoryNetConfig.unknown_logits', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("radii").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp_init', full_name='fewshot.configs.MemoryNetConfig.temp_init', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dense_update', full_name='fewshot.configs.MemoryNetConfig.dense_update', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gru_bias_init', full_name='fewshot.configs.MemoryNetConfig.gru_bias_init', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalize_feature', full_name='fewshot.configs.MemoryNetConfig.normalize_feature', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_ssl_beta_gamma_write', full_name='fewshot.configs.MemoryNetConfig.use_ssl_beta_gamma_write', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fix_unknown', full_name='fewshot.configs.MemoryNetConfig.fix_unknown', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown_id', full_name='fewshot.configs.MemoryNetConfig.unknown_id', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=40,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=560,
)

DESCRIPTOR.message_types_by_name['MemoryNetConfig'] = _MEMORYNETCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MemoryNetConfig = _reflection.GeneratedProtocolMessageType('MemoryNetConfig', (_message.Message,), dict(
  DESCRIPTOR = _MEMORYNETCONFIG,
  __module__ = 'fewshot.configs.memory_net_config_pb2'
  # @@protoc_insertion_point(class_scope:fewshot.configs.MemoryNetConfig)
  ))
_sym_db.RegisterMessage(MemoryNetConfig)


# @@protoc_insertion_point(module_scope)
