# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fewshot/configs/oml_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fewshot/configs/oml_config.proto',
  package='fewshot.configs',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n fewshot/configs/oml_config.proto\x12\x0f\x66\x65wshot.configs\"\x94\x03\n\tOMLConfig\x12\x13\n\x0bnum_filters\x18\x01 \x03(\x05\x12\x13\n\x0bnum_classes\x18\x02 \x01(\x05\x12\x10\n\x08inner_lr\x18\x03 \x01(\x02\x12%\n\x19inner_loop_truncate_steps\x18\x04 \x01(\x05:\x02-1\x12\x17\n\x0crepeat_steps\x18\x05 \x01(\x05:\x01\x31\x12 \n\x0finner_loop_loss\x18\x06 \x01(\t:\x07softmax\x12\x1b\n\x0eunknown_logits\x18\x07 \x01(\t:\x03max\x12$\n\x13unknown_output_type\x18\x08 \x01(\t:\x07softmax\x12$\n\x15select_active_classes\x18\t \x01(\x08:\x05\x66\x61lse\x12 \n\x11learn_weight_init\x18\n \x01(\x08:\x05\x66\x61lse\x12 \n\x11\x63osine_classifier\x18\x0b \x01(\x08:\x05\x66\x61lse\x12\x1d\n\x0f\x63lassifier_bias\x18\x0c \x01(\x08:\x04true\x12\x1d\n\x0esemisupervised\x18\r \x01(\x08:\x05\x66\x61lse')
)




_OMLCONFIG = _descriptor.Descriptor(
  name='OMLConfig',
  full_name='fewshot.configs.OMLConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_filters', full_name='fewshot.configs.OMLConfig.num_filters', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='fewshot.configs.OMLConfig.num_classes', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inner_lr', full_name='fewshot.configs.OMLConfig.inner_lr', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inner_loop_truncate_steps', full_name='fewshot.configs.OMLConfig.inner_loop_truncate_steps', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repeat_steps', full_name='fewshot.configs.OMLConfig.repeat_steps', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inner_loop_loss', full_name='fewshot.configs.OMLConfig.inner_loop_loss', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("softmax").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown_logits', full_name='fewshot.configs.OMLConfig.unknown_logits', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("max").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown_output_type', full_name='fewshot.configs.OMLConfig.unknown_output_type', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("softmax").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='select_active_classes', full_name='fewshot.configs.OMLConfig.select_active_classes', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learn_weight_init', full_name='fewshot.configs.OMLConfig.learn_weight_init', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cosine_classifier', full_name='fewshot.configs.OMLConfig.cosine_classifier', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classifier_bias', full_name='fewshot.configs.OMLConfig.classifier_bias', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='semisupervised', full_name='fewshot.configs.OMLConfig.semisupervised', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=458,
)

DESCRIPTOR.message_types_by_name['OMLConfig'] = _OMLCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OMLConfig = _reflection.GeneratedProtocolMessageType('OMLConfig', (_message.Message,), dict(
  DESCRIPTOR = _OMLCONFIG,
  __module__ = 'fewshot.configs.oml_config_pb2'
  # @@protoc_insertion_point(class_scope:fewshot.configs.OMLConfig)
  ))
_sym_db.RegisterMessage(OMLConfig)


# @@protoc_insertion_point(module_scope)
